% MergeandGenerateTable2.m:
% PURPOSE: A macro with the code to:
%   1) Merge simulation replications generated by SimforTab2.m into a
%   single .mat file for each policy (21 .mat files in total)
%   2) Compute the summary statistics across all simulation runs
%   3) Generate a table that includes summary statistics and save as a 
%   .mat file 
%
% OUTPUTS: Generates 21 .mat files for merged simulation results, and one 
% .mat file for the table that holds the summary statistics.
%
% WORKFLOW: Called in ReplicateFiguresRev1.m after defining sec64folder and
% calling SimforTab2.m

%%
cnames = {'Allocation Rule','Stopping Rule','E[Sampling Cost]','Standard error','E[Opportunity Cost]','Standard error','E[Total Cost]','Standard error','Prob. of Correct Selection','Total Computation Time','E[T]','E[Reward]','Standard Error', 'EVPI', 'Prob of stopping at t=0', 'Prob of reaching t=3000', 'Frac of low  early'};
NUMOFREPS = 1000; %number of replications for the simulation, 1000 in the paper
toCopyMat64(1, :) = cnames;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-Fixed1060', 'GPR', NUMOFREPS, sec64folder );
toCopyMat64(2, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-Fixed1060', 'GPR', NUMOFREPS, sec64folder );
toCopyMat64(3, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'Variance-Fixed1060', 'GPR', NUMOFREPS, sec64folder );
toCopyMat64(4, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-cPDE', 'GPR', NUMOFREPS, sec64folder );
toCopyMat64(5, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-cPDEUpperNO', 'GPR', NUMOFREPS, sec64folder );
toCopyMat64(6, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-cPDE', 'GPR', NUMOFREPS, sec64folder );
toCopyMat64(7, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-cPDEUpperNO', 'GPR', NUMOFREPS, sec64folder );
toCopyMat64(8, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-Fixed565', 'robust', NUMOFREPS, sec64folder );
toCopyMat64(9, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-Fixed565', 'robust', NUMOFREPS, sec64folder );
toCopyMat64(10, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'Variance-Fixed565', 'robust', NUMOFREPS, sec64folder );
toCopyMat64(11, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-cPDE', 'robust', NUMOFREPS, sec64folder );
toCopyMat64(12, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-cPDEUpperNO', 'robust', NUMOFREPS, sec64folder );
toCopyMat64(13, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-cPDE', 'robust', NUMOFREPS, sec64folder );
toCopyMat64(14, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-cPDEUpperNO', 'robust', NUMOFREPS, sec64folder );
toCopyMat64(15, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-Fixed595', 'tilted', NUMOFREPS, sec64folder );
toCopyMat64(16, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-Fixed595', 'tilted', NUMOFREPS, sec64folder );
toCopyMat64(17, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'Variance-Fixed595', 'tilted', NUMOFREPS, sec64folder );
toCopyMat64(18, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-cPDE', 'tilted', NUMOFREPS, sec64folder );
toCopyMat64(19, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cKG1-cPDEUpperNO', 'tilted', NUMOFREPS, sec64folder );
toCopyMat64(20, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-cPDE', 'tilted', NUMOFREPS, sec64folder );
toCopyMat64(21, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab2( 'cPDELower-cPDEUpperNO', 'tilted', NUMOFREPS, sec64folder );
toCopyMat64(22, :) = toCopy;
save(strcat(sec64folder,'Sec64-tab2.mat'),'toCopyMat64');