% PlotFigEC5.m:
% PURPOSE: A macro with the code to:
%   1) Merge simulation replications generated by SimforAppD1.m into a
%   single .mat file for each problem setup and each policy
%   (6x7=42 .mat files in total)
%   2) Generate a figure of power curves for each policy and save it as 
%   .fig and .eps 
%
% OUTPUTS: Generates 42 .mat files (6 policies, 7 problem setups), 
% one .fig file and one .eps files
%
% WORKFLOW: Called in ReplicateFiguresRev1.m after defining appdfolder and
% calling SimforAppD1.m

%% Merge data for each simulation replication to a single file for for each
%% policy and each problem setup
names = {'Upper','Lower','cKGstar','Upper-fixed','Lower-fixed','cKGstar-fixed'};
deltanames = {'03','05','07','09','11','13','15'};
NUMOFDELTAS = size(deltanames,2);
for i = 1:size(names,2)
    for j = 1:size(deltanames,2)
    load(strcat(appdfolder,'powercurve-21alt-',deltanames{j},'-',names{i},'.mat'))
    all.deltarule((i-1)*NUMOFDELTAS+j) = result;
    end
end
names = {'cPDEUpper - cPDEUpper', 'cPDELower - cPDELower', 'cKG* - cKG*', 'cPDEUpper - Fixed at 150', 'cPDELower - Fixed at 150', 'cKG* - Fixed at 150'};
deltas = 0.3:0.2:1.5;

%% Plot the power curve
PlotPowerCurve( all, names, deltas, appdfolder, strcat('PowerCurve','-','AppD1FigEC5') )
