% MergeandGenerateTable1.m:
% PURPOSE: A macro with the code to:
%   1) Merge simulation replications generated by SimforTab1.m into a
%   single .mat file for each policy (15 .mat files in total)
%   2) Compute the summary statistics across all simulation runs
%   3) Generate a table that includes summary statistics and save as a 
%   .mat file 
%
% OUTPUTS: Generates 15 .mat files for merged simulation results, and one 
% .mat file for the table that holds the summary statistics.
%
% WORKFLOW: Called in ReplicateFiguresRev1.m after defining sec63folder and
% calling SimforTab1.m

%%
cnames = {'Allocation Rule','Stopping Rule','E[Sampling Cost]','Standard error','E[Opportunity Cost]','Standard error','E[Total Cost]','Standard error','Prob. of Correct Selection','Total Computation Time','E[T]','E[Reward]','Standard Error', 'EVPI'};
toCopyMat63(1, :) = cnames;
[ toCopy ] = MergeReplicationsforTab1( 'cKG1-cKGstar', 100, 1000, sec63folder );
toCopyMat63(2, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cKG1-cPDELower', 100, 3000, sec63folder );
toCopyMat63(3, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cKG1-cPDE', 100, 5000, sec63folder );
toCopyMat63(4, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cKG1-cPDEUpperNO', 100, 5000, sec63folder );
toCopyMat63(5, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cKG1-fixed130', 100, 3000, sec63folder );
toCopyMat63(6, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cKG1-fixed200', 100, 5000, sec63folder );
toCopyMat63(7, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cKG1-fixed493', 100, 2000, sec63folder );
toCopyMat63(8, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cPDELower-cKGstar', 100, 1000, sec63folder );
toCopyMat63(9, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cPDELower-cPDELower', 100, 3000, sec63folder );
toCopyMat63(10, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cPDELower-cPDE', 100, 5000, sec63folder );
toCopyMat63(11, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cPDELower-cPDEUpperNO', 100, 5000, sec63folder );
toCopyMat63(12, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cPDELower-fixed150', 100, 3000, sec63folder );
toCopyMat63(13, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'cPDELower-fixed200', 100, 5000, sec63folder );
toCopyMat63(14, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'Variance-fixed150', 100, 1000, sec63folder );
toCopyMat63(15, :) = toCopy;
[ toCopy ] = MergeReplicationsforTab1( 'Variance-fixed200', 100, 1000, sec63folder );
toCopyMat63(16, :) = toCopy;
save(strcat(sec63folder,'Sec63-tab1.mat'),'toCopyMat63');