% MergeandGenerateTableEC2.m:
% PURPOSE: A macro with the code to:
%   1) Merge simulation replications generated by SimforTabEC2.m into a
%   single .mat file for each policy (4 .mat files in total)
%   2) Compute the summary statistics across all simulation runs
%   3) Generate a table that includes summary statistics and save as a 
%   .mat file 
%
% OUTPUTS: Generates 4 .mat files for merged simulation results, and one 
% .mat file for the table that holds the summary statistics.
%
% WORKFLOW: Called in ReplicateFiguresRev1.m after defining appc1folder and
% calling SimforTabEC2.m

%%
NUMOFREPS = 1000;
cnames = {'Allocation Rule','Stopping Rule','E[Sampling Cost]','Standard error','E[Opportunity Cost]','Standard error','E[Total Cost]','Standard error','Prob. of Correct Selection','Total Computation Time','E[T]','E[Reward]','Standard Error', 'EVPI'};
toCopyMatAppC(1, :) = cnames;
[ toCopy ] = MergeReplicationsEC2( 'cPDEUpper-cKGstar', 100, NUMOFREPS, appc1folder);
toCopyMatAppC(2, :) = toCopy;
[ toCopy ] = MergeReplicationsEC2( 'cPDEUpperNO-cKGstar', 100, NUMOFREPS, appc1folder);
toCopyMatAppC(3, :) = toCopy;
[ toCopy ] = MergeReplicationsEC2( 'cPDEUpper-cPDELower', 100, NUMOFREPS, appc1folder);
toCopyMatAppC(4, :) = toCopy;
[ toCopy ] = MergeReplicationsEC2( 'cPDEUpperNO-cPDELower', 100, NUMOFREPS, appc1folder);
toCopyMatAppC(5, :) = toCopy;
save(strcat(appc1folder,'AppC1-tabec2.mat'),'toCopyMatAppC');